#!/bin/bash
### SLURM batch script

### Email address
#SBATCH --mail-user=wle0001@uah.edu

### Job name
#SBATCH -J RHEAS_al

### Partition (queue), select shared or standard
#SBATCH -p standard

### TOTAL processors (number of tasks)
#SBATCH --ntasks 1

### total run time estimate (D-HH:MM)
#SBATCH -t 10-23:00

### memory (GB per CPU)
#SBATCH --mem-per-cpu=64G

### Mail to user on an event
### common options are FAIL, BEGIN, END, REQUEUE
#SBATCH --mail-type=END,FAIL

### Ouput files
#SBATCH -o slurm_out/slurm_al.out # STDOUT
#SBATCH -e slurm_out/slurm_al.err # STDERR


echo "Starting at `date`"
echo "Running on hosts: $SLURM_NODELIST"
echo "Running on $SLURM_NNODES nodes."
echo "Running on $SLURM_NPROCS processors."
echo "Current working directory is `pwd`"
echo

### Add your module statments here
module load python/v3
module load postgis

conda activate /rgroup/drought/rheas-env
#echo "create database tn template rheas" | psql -h matrix1 -d rheas
#rheas -d al -u /nas/rgroup/drought/RHEAS/SE_init/data.conf
rheas -v -d al /nas/rgroup/drought/RHEAS/SE_data/AL/confs/AL_nowcast_test.conf
chmod -R g+rwx /nas/rgroup/drought/RHEAS/slurms/tmp* 
#python tmp.py
